import 'dotenv/config';
import fs from 'fs';
import path from 'path';
import OpenAI from 'openai';

const TOPICS = [
  "Philosophy of Life",
  "Emerging Technology Trends",
  "Modern Web Development & Coding",
  "Mental Health for Developers",
  "Productivity & Career Growth",
  "Trending Tech News",
  "The Future of AI"
];

const GUIDE_PATH = path.join(process.cwd(), 'src/app/blog/BLOG_WRITING_GUIDE.mdx');
const POSTS_DIR = path.join(process.cwd(), 'src/app/blog/posts');

async function main() {
  console.log("🚀 Starting Daily Blog Generation...");

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    console.error("❌ Error: OPENAI_API_KEY is not set in environment variables.");
    console.error("   Please create a .env file or set the secret in GitHub Actions.");
    process.exit(1);
  }

  const openai = new OpenAI({ apiKey });

  // 1. Read the Guide for context
  let guideContent = "";
  try {
    guideContent = fs.readFileSync(GUIDE_PATH, 'utf-8');
  } catch (error) {
    console.warn("⚠️ Warning: Could not read BLOG_WRITING_GUIDE.mdx. Proceeding with minimal context.");
  }

  // 2. Pick a random topic
  const topic = TOPICS[Math.floor(Math.random() * TOPICS.length)];
  console.log(`📌 Selected Topic: ${topic}`);

  // 3. Construct Prompt
  const prompt = `
You are an expert technical writer and blogger for a developer portfolio.
Your task is to write a high-quality, engaging, and useful blog post in Indonesian (Bahasa Indonesia).

TOPIC: ${topic}

REQUIREMENTS:
1. **Language:** Indonesian (Informal but professional, like a tech influencer or senior dev sharing knowledge).
2. **Format:** MDX (Markdown with JSX components).
3. **Frontmatter:** You MUST use the exact frontmatter format defined below.
4. **Components:** Use the custom components (<CodeBlock />, <SmartImage />, etc.) where appropriate.
5. **Length:** Medium to Long (approx. 500-1000 words).
6. **Tone:** Insightful, helpful, slightly witty.

REFERENCE STYLE GUIDE (Follow this strictly for schema):
${guideContent}

OUTPUT RULES:
- Return ONLY the raw MDX content.
- Do NOT wrap it in \`\`\`markdown code blocks.
- The first line must be the opening "---" of the frontmatter.
- For the 'tag' field in frontmatter, choose the most appropriate one from: "Journal", "Tips", "Career & Mindset", "Documentation".
- The 'publishedAt' date should be today's date in YYYY-MM-DD format.
- Ensure the 'slug' (filename) will be derived from the title later, so make the title catchy but clear.
`;

  console.log("⏳ Generating content with OpenAI...");

  try {
    const completion = await openai.chat.completions.create({
      model: "gpt-4o", // Or gpt-4o-mini for cost savings
      messages: [
        { role: "system", content: "You are a helpful assistant that writes MDX blog posts." },
        { role: "user", content: prompt }
      ],
      temperature: 0.7,
    });

    const content = completion.choices[0].message.content;

    if (!content) {
      throw new Error("No content generated by OpenAI.");
    }

    // 4. Parse content to extract Title for filename
    // We expect the first few lines to contain title: "..."
    const titleMatch = content.match(/title:\s*["'](.+?)["']/);
    let filename = `daily-post-${Date.now()}.mdx`;

    if (titleMatch && titleMatch[1]) {
      const title = titleMatch[1];
      // Convert title to kebab-case slug
      const slug = title
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '') // remove special chars
        .trim()
        .replace(/\s+/g, '-');

      const today = new Date().toISOString().split('T')[0];
      // Filename format: YYYY-MM-DD-slug.mdx (optional date prefix, but good for sorting)
      // The guide examples didn't strictly force date prefixes, but user wants "daily updates", so date prefix helps uniqueness.
      filename = `${today}-${slug}.mdx`;
    }

    // Ensure output directory exists
    if (!fs.existsSync(POSTS_DIR)) {
        fs.mkdirSync(POSTS_DIR, { recursive: true });
    }

    const filePath = path.join(POSTS_DIR, filename);

    // Clean up potential markdown code block wrapping if the LLM ignored instructions
    let cleanContent = content;
    if (cleanContent.startsWith('```markdown')) cleanContent = cleanContent.replace(/^```markdown\n/, '');
    if (cleanContent.startsWith('```mdx')) cleanContent = cleanContent.replace(/^```mdx\n/, '');
    if (cleanContent.startsWith('```')) cleanContent = cleanContent.replace(/^```\n/, '');
    if (cleanContent.endsWith('```')) cleanContent = cleanContent.replace(/\n```$/, '');

    fs.writeFileSync(filePath, cleanContent, 'utf-8');
    console.log(`✅ Blog post generated successfully!`);
    console.log(`📂 Saved to: ${filePath}`);

  } catch (error) {
    console.error("❌ Error generating blog post:", error);
    process.exit(1);
  }
}

main();
